---
#-------------------------------
# General Site Settings

title: H20J
logo:
author: HOMAWOO Joseph
description: This appliction is my portfolio
email: homawoojoseph@gmail.com
phone: +228 99152480
address: LOME,TOGO
copyright: Copyright &copy; 2022 powered by [Themefisher](https://themefisher.com) 

menu:
  - { name: About, link: "/about" }
  - { name: Blog, link: "/blog" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics:  UA-183646927-1

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: jerrykel

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Joseph HOMAWOO <br> Developer back-end and UX designer From LOME

social:
  - { icon: "ti-facebook", link: "https://web.facebook.com/fernando.vilarios" }
  - { icon: "ti-instagram", link: "https://www.instagram.com/_jerrykel/" }
  - { icon: "ti-twitter", link: "https://twitter.com/Jerrykel_j" }
  - { icon: "ti-github", link: "https://github.com/novenopatch/" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: Lorem ipsum dolor sit amet, consectetur adipisicing elit,
 sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.

blurb-btn-link: "/about"
blurb-btn-name: know more

# About Page

# Work Process Section
work-process:
  - title: "Research and Plan"
    icon: "assets/images/icons/plan.png"
    content: "TODO 1"
  - title: "Design and Develop"
    icon: "assets/images/icons/design.png"
    content: "TODO 2"

  - title: "Deliver"
    icon: "assets/images/icons/print.png"
    content: "TODO2"

# My Team Section
team:
  - title: "Joseph HOMAWOO"
    image: "assets/images/team/member-1.png"
    designation: "Back-End Developer && UX Designer"
    linkedin: ""


  - title: "John Doe"
    image: "assets/images/team/member-3.png"
    designation: "Designer and Front-End Developer"

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: Java/Kotlin & Javafx, color: "#5473e6", value: "80%" }
  - { name: Android & Flutter, color: "#fdb157", value: "70%" }
  - { name: PHP & Symfony , color: "#fbb157", value: "80%" }
  - { name: Python & Django  , color: "#9473e6", value: "80%" }
  - { name: HTML/CSS/JS , color: "#fcbcaa", value: "70%" }
  - { name: Git & Docker , color: "#ffccaa", value: "80%" }
  - { name : Firebase and Aws, color: "#f473e6", value: "60%"}
  - { name: Adobe Xd, color: "#bdecf6", value: "70%" }

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name: Technician Software,
      icon: "icon-2.png",
      date: "JAN 2020 - Dec 2020",
      organization: "SIMPLEMENT VOTRE",
      url: "",
    }
  - {
      name: Junior UX & UI Designer,
      icon: "icon-2.png",
      date: "JAN 2021 - Feb 2021",
      organization: "SANAM-Group",
      url: "",
    }
  - {
      name: Back-End and Mobile Developer,
      icon: "icon-2.png",
      date: "Aug 2021 - Present",
      organization: "SANAM-Group",
      url: "",
    }

#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: Licence ,
      date: "2023",
      organization: "LOME University",
      url: "",
    }
  - {
      name: Higher Secondary Certificat,
      date: "2019",
      organization: "LOME City High School",
      url: "",
    }


#-------------------------------
# Services Section

services-title: Services
services:
  - {
      name: UI Design,
      icon: ti-palette,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      active: true, # Add true to select section
    }
  - {
      name: Software Engineering,
      icon: ti-panel,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      active: true, # Add true to select section
    }
  - {
      name: UX Design,
      icon: ti-vector,
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      active: true, # Add true to select section
    }
  

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/signals.png"
    url: "#"

  - image: "assets/images/portfolio/safe.png"
    url: "#"

  - image: "assets/images/portfolio/snake.png"
    url: "#"

  - image: "assets/images/portfolio/space.png"
    url: "#"

  - image: "assets/images/portfolio/superquiz.png"
    url: "#"

# Portfolio Page
portfolio-label:
  - { title: "Mobile App ", type: "Mobile developement" }
  - { title: "Dektop App ", type: "Desktop developement" }
  - { title: "Web App ", type: "Web developement" }
  - { title: "Game", type: "Game developement" }
  - { title: "UI/UX Design", type: "design" }
  - { title: "ILLUSTRATION", type: "illustration" }

portfolio-items:
  - image: "assets/images/portfolio/signals.png"
    url: "#"
    portfolio-type:
      - type: "Mobile developement"
      - type: "design"

  - image: "assets/images/portfolio/safe.png"
    url: "#"
    portfolio-type:
      - type: "Mobile developement"
      - type: "design"

  - image: "assets/images/portfolio/snake.png"
    url: "#"
    portfolio-type:
      - type: "Game developement"

  - image: "assets/images/portfolio/space.png"
    url: "#"
    portfolio-type:
      - type: "Game developement"

  - image: "assets/images/portfolio/superquiz.png"
    url: "#"
    portfolio-type:
      - type: "Mobile developement"
      - type: "Game developement"
      - type: "design"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"

  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"

  - image: "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."


#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/sanam-logo.png"
    url: "www.sanam-group.com"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: homawoojoseph@gmail.com
