---
#-------------------------------
# General Site Settings

title: AGRI-INNOV
logo:
author: Prince Konu
description: This application is 
email: agrinnov mail
phone: your phone
address: LOME,TOGO
copyright: Copyright &copy; 2023 Build with<span style="color:red"> ♥</span> By<a style="color:red" href="https://bluetech-tg.github.io/" target="_blank"  rel="noopener noreferrer"> BlueTech.</a> All Right Reserved.
menu:
  - { name: About, link: "/about" }
 # - { name: Blog, link: "/blog" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Contact, link: "/contact" }
  #- { name: CV, link: "/cv" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics:  UA-183646927-1

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: jerrykel

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Prince Konu <br> ...... From LOME

social:
  - { icon: "ti-facebook", link: "https://web.facebook.com/fernando.vilarios" }
  - { icon: "ti-instagram", link: "https://www.instagram.com/_jerrykel/" }
  - { icon: "ti-twitter", link: "https://twitter.com/Jerrykel_j" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: description.
blurb-btn-link: "/about"
blurb-btn-name: en savoir plus

# About Page

# Work Process Section
work-process:
  - title: "Research and Plan"
    icon: "assets/images/icons/plan.png"
    content: "We collect information to understand your needs and your expectations and then we define the strategy and plan"
  - title: "Design and Develop"
    icon: "assets/images/icons/design.png"
    content: "We oofer different prototypes designer by our designers and we develop your choice"

  - title: "Deliver"
    icon: "assets/images/icons/print.png"
    content: "We are improving,we test then we deliver"

# My Team Section
team:



 # - title: "John Doe"
 #   image: "assets/images/team/member-3.png"
 #   designation: "Designer and Front-End Developer"

#-------------------------------
# Skills Section

skills-title: Savoir faire
skills:
  - { name: Redaction de project, color: "#5473e6", value: "80%" }
 
#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
 
#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: Licence ,
      date: "2023",
      organization: "LOME University",
      url: "https://etu.univ-lome.tg/",
    }
 

#-------------------------------
# Services Section

services-title: Services
services:

  - {
      name: redation de project,
      icon: ti-panel,
      description: "description",
      active: true, # Add true to select section
    }
  
  

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
 

 
# Portfolio Page
portfolio-label:
 

portfolio-items:
  

 

#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "<strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."


#-------------------------------
# Client Slider Section

client-slider-items:
 


#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: prince send me your mail
